load("//bzl/valdi:valdi_cli_application.bzl", "valdi_cli_application")
load("//bzl/valdi:valdi_module.bzl", "valdi_module")

valdi_module(
    name = "ssr_example",
    srcs = ["index.tsx"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/valdi_modules/src/valdi/valdi_core",
        "//src/valdi_modules/src/valdi/valdi_ssr",
    ],
)

valdi_cli_application(
    name = "server",
    script_path = "ssr_example/index",
    deps = [":ssr_example"],
)
