load("@valdi//bzl/valdi:valdi_module.bzl", "valdi_module")

valdi_module(
    name = "client_sql_smoke",
    srcs = glob([
        "src/**/*.ts",
        "src/**/*.tsx",
    ]) + [
        "tsconfig.json",
    ],
    android_output_target = "release",
    ios_module_name = "SCCClientSQLSmoke",
    ios_output_target = "release",
    sql_db_names = ["TestDb"],
    sql_srcs = glob([
        "sql/**/*.sq",
        "sql/**/*.sqm",
        "sql/sql_types.yaml",
        "sql/sql_manifest.yaml",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/valdi_modules/src/valdi/client_sql",
        "//src/valdi_modules/src/valdi/valdi_core",
    ],
)

filegroup(
    name = "clientsql_generator_test_data",
    srcs = ["src/ClientSQLSmoke.ts"],
    testonly = True,
    visibility = ["//compiler/clientsql:__pkg__"],
)
